name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Generate Changelog
        uses: jaywcjlove/changelog-generator@v1.4.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ steps.create_tag.outputs.version }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - run: yarn install
      # - name: HelloWorld -> Build Android Release
      #   working-directory: HelloWorld
      #   run: cd android && ./gradlew assembleRelease

      - run: yarn run start
      - run: git status

      - run: npm i markdown-to-html-cli -g
      - run: mkdir -p build
      - run: markdown-to-html --output build/index.html

      - run: npm install @jsdevtools/npm-publish -g
      - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./template/package.json

  release:
    runs-on: ubuntu-18.04
    needs: build-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Is a tag created auto?
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./template/package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.4.8
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ steps.create_tag.outputs.version }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.changelog.outputs.tag }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-native-template@${{steps.changelog.outputs.version}}/file/README.md) [![npm version](https://img.shields.io/npm/v/@uiw/react-native-template.svg)](https://www.npmjs.com/package/@uiw/react-native-template)
            
            ```bash
            npm i @uiw/react-native-template@${{steps.changelog.outputs.version}}
            ```

            ${{ steps.changelog.outputs.compareurl }}
            
            ${{ steps.changelog.outputs.changelog }}
